version: '3'

tasks:
  run:
    deps: [run:ui, run:keycloak]
    desc: runs all services
    cmds:
      - echo "stopped"

  run:go:
    deps: [run:stats, run:redirector, run:api]
    desc: run backend
    cmds:
      - echo "stopped"

  run:dev:frontend:
    deps: [run:go, run:keycloak]
    desc: runs services for ui dev
    cmds: 
      - echo "stopped"

  run:keycloak:
    desc: start docker-compose
    cmds:
      - docker-compose up

  run:stats:
    desc: Runs Go backend
    cmds:
      - go run cmd/stats/main.go

  run:api:
    desc: Runs Go backend
    cmds:
      - go run cmd/usercodes/main.go

  run:redirector:
    desc: Runs Go backend
    cmds:
      - go run cmd/redirecter/main.go


  run:ui:
    desc: runs ui
    dir: ./ui
    cmds:
      - npm run start

  update:
    desc: updatesm deps
    cmds:
      - task: update:go
      - task: update:npm

  update:go:
    desc: updates go deps
    cmds:
      - go mod tidy

  update:npm:
    desc: updates js deps
    dir: ./ui
    cmds:
      - npm install 
